language: node_js
node_js:
- '10.8'
deploy:
  provider: cloudfoundry
  username: nmdsdevopsserviceadm@hotmail.com
  password:
    secure: hJblXgCCVBDM6EgoF3WwQS3Yy3S3a/o6vm2yQFJ/tR6ixf/Nu1t36tyMQVaIdreXHjivPr3tjPbqUC0MBTqSY+eNOi49NhWETXiODHW8T28G8co6XklRhq3gVF2/ni9Y4totFM5Whed0dEAppTomfLj4E724IaPjKrhpmymL/lU6T+1H8ur3o2qifvg+hW8We/eTGfXzIGlML+fb9cLbb4gfIcXx0O1dxkDESlUN5D7iQJeIv6mW48L/ZFJAF01HTIt6E6ZTvu6qZprSWbBku8wWYKsBkXDHjD254jSMUEmtdPEqFwdwB95Eomk9uIKkdrwbAtZlHnlGuGhU1+jhNvE+fGVJyexAl2aqZ71Y750hWfY+cyFgUlvlDfF/cqzuUYEo67fQDz8tStVyPb5GLRo9uUT+QFRXiMRL+BLKTEvUzQpe4hQTncjZdqgWDij7sX2ZOHLtCdGXAyrz2qcH+dhDe3xcCf/9JM6dHFTSwTNZUDp91/qeoAKoH0FyN7xLT6b0XArHqDeIrsRj9IHi/y25KZ7CSCKXZUXhc/ALKaxWOeCR64kfMbVJ8/5l08kuT0zMo/d1W7pd6AtI/balW+BMYeuYHocQ9YTF3SyOPatepWrL1RW5QrgcLWcc80hkNy/+0sizrDuCkYzSeDNj19x3Hxod+odrzGVx35kI7tM=
  api: https://api.cloud.service.gov.uk
  organization: dhsc-skills-for-care-nmds-sc-2
  space: sandbox
