language: node_js
node_js:
    - 'iojs'
    - '10.8'
env:
  secure:       nQQyoy69UZl4wxe5lDUi7QNuX01yy9IqT7ZaVy5d8+EtM/z2/cMlGGWGD6uFV45i5OncGvKbu/8Gy/mZkrFGY4nkdhukIIaZ1DNtD4D++9oecH1nmFUJ0f05Lhj60y6I9m54n/5wKfvdkU0AWSMHxJmWlv5xVU5+joz+AV3lrcPrbASTs3lFhDMZ9yPV1ZtWDoQn/0caZauh+I5qnmc6Q3WWHOcYYiQ12emIGMEj6YRk5i23czX3IyS18vsKTidUATTY8zq88JEs66g+feGAhf6xJ120kiDySq4vY8SEBexbpcaBS8IZxjBF2U8zxLbdzcdqQahY+Sllwk9behiTvdu/1jgQifwTN7rFFpIBMfcZGA1nKXdUiugREHjAsprBYuHQ3VKvnGBjZP0y54yqZMf3/pWN3j4PO64pcD37eBp+iaguG30E6xlXvUnkp2o3njiOERHxNLawwz78WQ8ikkFgtVztbAhIXzChGTHWH3kAwmZ0YCMKYA2/MaRT2EwePsruBTLn9Q8LZO+QfXW8TR41+K4cqsDwARJ0xj2rRPnQXf8L2fFkcL7ustN4S7+K0Xu8JVC6aWmaCJGHRjkXFiTiH0wpeJNAdsWuaTe57L640fQjzqBTeI5tCNoQYPOhRuzfwa7N74ljOOKyyPFJGZAZv4JO8OLnCtT9ZLcgcq0=
deploy: 
    edge:true 
    provider:cloudfoundry 
    username:nasir.m@hotmail.co.uk 
    api:https://api.cloud.service.gov.uk
    organization:dhsc-skills-for-care-nmds-sc-2 
    space:sandbox
