language: node_js
node_js:
- iojs
- '10.8'
deploy:
  provider: cloudfoundry
  username: nasir.m@hotmail.co.uk  
  Password: "VaTYe4WkrFz7IJrEEOP4pxqvhQUjHKwq4rzYAPwgv4wDbl2hHZ/Zu/ZFcRzMH+FBl5P/rl/xNedH/ZUhh2jkJjSMGPbDg+NGtFz5ND1cLnI/TdmFebey2XGaGj4McM7Jl8qSf7vpuCnKPVhlCro4989oT4ajuoriOo94UwpP54iLqpRfIh/ccF5tNo31Np88E2mZiDHHGSY0q9lQdIyNmHmPUD8cOCAAQnCwezh18GwTh4mE8fBlQGbCYvXBehj31MO5P2qIhruUCHQE8uPRHmUmyBc5VHD1lfbl3N7wWipVaYBOAOCJ97ooSa5V6nR7TtHqxsoB7PrGOMCXZqnMPoMbundHui9DuqR3TxWsZEGFE3mDded0ZhckoPqX56nZMOOWeDtWoi2UXzLHqz8CAOL8AsOnF1ocgdeAJLkIi5vogV5oGmqJxRwuvliL510rEjnW3qcVNWAS58F4K9Jw5BzPpR2D6E3mZbLxZkXD6N1kQxo5f+mp4G+/BX7ncKkRY/H793V3nk1w5Of4I2YQWz3J7RQxl0NpqGZU+tUxHIrq1UHI3n+yAyrUWGpatHaN3RFPuI+CL6lG4g4Yri+s2yOsRr0cA6Naia//HeZDrWi/E7mGkp9Xd4ZAVmHhB1adqRnqTLlYDGhOt/E6+QcHQ/IWPZv9/8rAaqg0yuW6wVw="
  api: https://api.cloud.service.gov.uk
  organization: dhsc-skills-for-care-nmds-sc-2
  space: sandbox
  
  
