language: node_js
node_js:
- '10.8'
deploy:
  provider: cloudfoundry
  username: nasir.m@hotmail.co.uk
  password:  
    secure: "SuULwjJUslVHKUr9BNe81GxSf9RYvRtm4jnsl66opWgcXEgH7lCAkpgKi7PWJ7GZTpA1OXjmyvqyAdJTaHKfPpN9kPOE4tOYniG5UHNUlhOb74Tui6r7aVykVanNicPkX6pozuRXmaPrCZY3HfoDJb8P4OErvHP8i0qXfmul87wW8HKc5mTlcngZkteVaiYUZtIFxaLRrMnxygZqgploDmBAdpNxVdO++yM0ObiOM1iPQ7FaWUO/+QvzOr2bN1cWkAOqjFwPP/R/hZ3sUJmzXEIGO6I9MtzKHKznU91CTYv3Yc26L5WimKRRZKADny9Qx814Fsb+gkl9BRAIJqrOlWug1c+CPD20sjZdbgrliHWSaQfDgGKAAwI6esyG6GQDYtmgjIEUmG3FXPmW7XqePJl+nCkKp6H00vwQolePv9GwIRztvdoBkqwa1uqvT12UjG2boUoI3ASNSWTrLyHlW75D5trieAVAWrfb3w/QsU7d2CS/W4T3mcG2UbM8Dig0FpyqwvGGStUMxTDsHKxgdr2o5++rIvfkBMMeuc8XQIfDpWyKJPdjvlWkPbeFqFfLEFLgB2Iux8nVDUD3ZoJl4UCMH1AgHRdjfCiMwYWyETbnZVhwQhsPjA1PLyQ7lCk8B9vnTiJsxccRH7GAYfEL1zfMWl1TXyY02HnDPjOz6WY="
  api: https://api.cloud.service.gov.uk
  organization: dhsc-skills-for-care-nmds-sc-2
  space: sandbox
