language: node_js
node_js:
- iojs
- '10.8'
deploy:
  provider: cloudfoundry
  username: nasir.m@hotmail.co.uk
  api: https://api.cloud.service.gov.uk
  organization: dhsc-skills-for-care-nmds-sc-2
  space: sandbox
  password:
    secure: um2zhiPGJNOEx6TG/MHbVF1fzUMgRSybO7t76+oCoMA1nd4r69AmyDPseN2zywt6/9nzx5sX+VPHEub753OzNu++9iESUhvz3cVC9ry/hh7v7BvyY+vGDS5lctBlW+0QqHlGgT2rlcbQ2o12Rc0x+a5xW6R1Ro1a+f7HE9v00LhabPE/LIc8eBishbnp8gffsNv4YFAbgTqcbIMCC/WwQ/wYtvUM5GKCYspivsLsY1pkcQHdv8cGwyKdhZwomnUOnIGarjmqMCY80sHekk9Y/TKx8XyGrx4GR8nsq4pZnpA+APLGi90k9mLtSFE2FeOKoVDBv9Rclql0wgoWpFZQNHEtd8Ou7rw0aiygatfgng2Os69e0Zy/uuXSZlIgg3nYOesuVwzQVh/LT1XCiphF2hVBHF5g5FAPhR3RBKs5EL8ai0IxD4zhITFZsKnREyQ+3MvYaHsfEwb8TrHGt82mHt5YfNpShiXzdmnQvPj9EbQdKy0HYIV82ZXCfbncQkFtovwzDUfpIjQ1N3HJ0HXiLALiwQWCTpsMeZo71p0IFp0nYF3IvD03sceYO9HRRNtP2WpyZcicAGwanaZexpZ7jOu7DKtRYVJ9iGV0flYx/0k+pBuLfg1x9RjtEnl87lT8ZpHwedNxRNMdv6k2M6S78I6tMVm2QO6QdSEqqf0KYbk=
