language: node_js
node_js:
- '10.8'
deploy:
  provider: cloudfoundry
  username: nasir.m@hotmail.co.uk
  password:
    secure: "UxXi/u8+CCJOfp3iXW470WLmt9jw0PHMeNJ4/XRQ+YRAZrrzV6AraIIrU/aGiYDAp+kQSIbjFOatN+xpo+DUg0ou44hDwGxseEfrEPCTm8EylCuvURVWwYcCBgtflkxsb+/A/PsivFT5DAD1WvB+c8T8tbF4FF6btS3gY6kBn9Vq2fNPtXE0GUc1mTQTwHwPVMQEAe/Zkekgzp1GE24kgqhcEX2VJUO/8sV/Aj5xaIWi12RDFWN4S1oahvcup9D3UrLRc8FVwuJDICPJTJFahLvmJph3Gj1vzd1hxT6HpzhxQCcKZOx22frbxPhospF8yS+9877myWwwLMu7v+VzLZ0wNUxDty1NA6ZnSR2jPwKVxJjjXPyAWO6Wu9KeWWJ7jN4cNSlNFrdZVYDeowma9OU7YgnBk0m6fL4Kc4jwPCWyW+6N4/h0rEp4WE0hZXM7As+k5rLLupqNuE8LprapJAhlChg4azvx+UFvs2u6nbHH/96aD5b6ZDB0NQgKoVrjtFEuYd8Ii8Ply+8otYZ4Bc2joPttXpYH1/Yy9BdVrHFDLVspTbEF7QvcGyhe0Ed2mZ8aUJxUV9tPVIRf6GxitzsFkSZ6BgeVTKqf+nn0SHadWRiVGAPl2BbaNL+vY2Tb3UAW1MnlprexvboQgQDM2FRziZaGKCef/7YtvPGgDEU="
  api: https://api.cloud.service.gov.uk
  organization: dhsc-skills-for-care-nmds-sc-2
  space: sandbox
