slack:
    level: 0    # disables Slack notifications
jwt:
    iss: 'localhost'
    ttl:
        login: 60
db:
    pool: 5
    ssl: false
log:
    sequelize: false
aws:
    enabled: true
    kinesis:
        enabled: true
        workers: wokers.dev
    sns:
        enabled: true
        registrations: 'arn:aws:sns:eu-west-1:364648107127:registrations-dev'
        feedback: 'arn:aws:sns:eu-west-1:364648107127:feedback-dev'