slack:
    level: 0    # disables Slack notifications
jwt:
    iss: 'localhost'
db:
    pool: 5
    ssl: false
    client_ssl:
        status: true
        certificate: 'E:/aylingw.crt'
        key: 'E:/postgresql.key'
        ca: 'E:/root.crt'