slack:
    level: 0    # disables Slack notifications
jwt:
    iss: 'localhost'
    ttl:
        login: 60
db:
    pool: 5
    ssl: false
log:
    sequelize: false
aws:
    enabled: true
    kinesis:
            enabled: true
    sns:
        enabled: true