slack:
    level: 0    # disables Slack notifications
jwt:
    iss: 'localhost'
    ttl:
        login: 60
db:
    pool: 5
    ssl: true
    host: 3.8.213.218
    database: orclpg
    username: postgres
    password: zaq12wsx

    client_ssl:
        status: true
        # certificate: 'E:/mycert.crt'
        # key: 'E:/mykey.key'
        # ca: 'E:/myca.crt'
        certificate: '/home/aylingw/Documents/work/wozitech/steria/s4c/Documents/tribal/aylingw.crt'
        key: '/home/aylingw/Documents/work/wozitech/steria/s4c/Documents/tribal/postgresql.key'
        ca: '/home/aylingw/Documents/work/wozitech/steria/s4c/Documents/tribal/root.crt'
log:
    sequelize: false
