aws:
    region: eu-west-1
    secrets:
        use: true
        wallet: prod/api

slack:
    level : 3     # enables Slack notifications

jwt:
    iss: 'asc-wds.skillsforcare.org.uk'
    ttl:
        login: 5

db:
    pool: 15
    ssl: true
    username: sfcapp
    client_ssl:
        status: true
        usingFiles: false

notify:
    replyTo: '44e98371-2e44-4c6b-ad76-235136be0f8a'
    templates:
        resetPassword: 'fd430f0d-6609-400a-b171-cf124453ec1c'
        addUser: 'f20e9cbe-920d-4b1f-b05d-bac1ca8d5b54'

bulkupload:
    region: eu-west-2
    bucketname: sfc-bulkupload-prod

public:
    download:
        baseurl: https://sfc-public-prod.s3.eu-west-2.amazonaws.com/public/download
