slack:
    level : 3     # enables Slack notifications
jwt:
    iss: 'sfcstaging.cloudapps.digital'
notify:
    replyTo: '73711295-a4da-4303-9127-65be2a409681'
    templates:
        resetPassword: 'f2c43610-9ec9-4271-b9b1-dd55569b191c'